### ISSUE TITLE
Add capability to close an open Accordion

### ISSUE THREAD

**Issue by kavinda1995** [rhinobase/raftyui#51]
Right now, the according component can be opened but it cannot close itself without any other accordion item of it's group is opened.

Item 1 opened:
![image](https://github.com/rhinobase/raftyui/assets/19621533/e545d13a-0f04-4434-94e3-d7429998eccf)

Item 1 closing only when item 2 opened
![image](https://github.com/rhinobase/raftyui/assets/19621533/bca49688-6a6d-41ed-ad83-5fcc02e6cf3a)

IMO - it's better if we can make any accordion can close themself.

**Would love to open a PR for this if this is approved**

**Comment by MathurAditya724** [comment]
Hey @kavinda1995, have you tried using the `collapsible` prop? Here you can check this example - https://rafty.rhinobase.io/docs/components/accordion#collapsible
